---
listen:
  port: 55755
mysql:
  db: pal4
  host: mysql
  port: 3306
  user: pal4
  pass: 6Nck5Xrpi8Km6ZqZJApz
redis:
  host: redis
  port: 6379
  db: 5
  pass: pFG64SBbhGB56K8Cv5eZbrdQ
logfile: logs/pal4.log
